### ISSUE TITLE
jquery clone() issue

### ISSUE THREAD

**Issue by idevwebs** [danielfarrell/bootstrap-combobox#177]
Great combobox! 

Working good when used normally, but I can't seem to get cloned comboboxes to work. Currently in a table row that gets cloned with "Add Row" and the clone happens, but the dropdown button does nothing on the new box, but instead activates the dropdown on the original combobox.

Any suggestions?

Thanks!

UPDATE:

Worked by: 
clone() NOT clone(true)
find('div.combobox-container').remove();
find('.combobox').combobox();

**Comment by MerlyLau** [comment]
I have this issue too now, do you have resolved it? Thank you!

**Comment by seanVonDrake** [comment]
please help, I have the same issue here... tried with:
clone() NOT clone(true)
find('div.combobox-container').remove();
find('.combobox').combobox();

but still don't work... what is the proper way to clone?
otherwise, there is a way to destroy the combobox before clone, so it can be attached again after?
