### ISSUE TITLE
Is it possible to utilize the `items` feature from typeahead?

### ISSUE THREAD

**Issue by dannylloyd** [danielfarrell/bootstrap-combobox#69]
Bootstrap Typeahead has a feature to limit the number of items to display at a time, is this part of your combobox? I do see that the default behavior of a dropdown is to show all the items at one time, but I was hoping it was implemented in this library.

**Comment by flgis2cool** [comment]
Hi Daniel,  I am looking at this same issue with an employee combobox and want to limit the amount of records coming back because it is causing slow down issues when loading the combobox with all the records in order for it to search.  Did you look into adding the above functionality I see this was posted on back in 2013?

**Comment by dannylloyd** [comment]
@flgis2cool I ended up using select2 and loading from a remote data source which allowed me to filter the results. http://select2.github.io/select2/#ajax. I hope this is still useful 5 months later
